---
version: 1
jobs:
  test1:
    steps:
      - cmd: echo $SHELL

  test2:
    shell: /bin/bash -x
    steps:
      - cmd: echo $SHELL
      - cmd: pwd && ls
      - name: with dir
        cmd: pwd && ls
        dir: /

  test3:
    shell: /bin/zsh
    env:
      - ENV_TEST_1=hoge
    steps:
      - name: show ENV_TEST
        cmd: env | grep ENV_TEST
        env:
          - ENV_TEST_2=huga
      - name: override ENV_TEST
        cmd: env | grep ENV_TEST
        env:
          - ENV_TEST_1=huga

  test4:
    steps:
      - name: OK 1
        cmd: echo OK 1
        if:
          - file:
              exists: /etc/resolv.conf
      - name: NG 1
        cmd: echo NG 1
        if:
          - file:
              exists: /etc/resolv.conf.hoge
      - name: OK 2
        cmd: echo OK 2
        if:
          - file:
              exists: /etc/resolv.conf
          - directory:
              missing: ./ABCDEFG

  test5:
    steps:
      - name: OK 1
        cmd: echo OK 1
        if:
          - env:
            - HOGE=1

  test6:
    env:
      - HOGE=0
    steps:
      - name: OK 1
        cmd: echo OK 1
        if:
          - env:
            - HOGE=1

  test7:
    # shell: cmd.exe
    steps:
      - cmd: |-
          dir
      - cmd: dir
        dir: C:\Windows
      - cmd: |-
          wmic path Win32_PnPEntity where "DeviceID like '%%SWD\\SCDEVICEENUM\\%%'" get Caption,DeviceID,Manufacturer,PNPClass

  test8:
    shell: powershell.exe
    steps:
      - cmd: |-
          dir
      - cmd: dir
        dir: C:\Windows
      - cmd: |-
          wmic path Win32_PnPEntity where "DeviceID like '%%SWD\\SCDEVICEENUM\\%%'" get Caption,DeviceID,Manufacturer,PNPClass

  test9:
    steps:
      - use: mohemohe/lscbuild-plugin-sandbox
